subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 2
      leftSlaveOne: -1
      leftSlaveTwo: -1
      rightMain: 1
      rightSlaveOne: -1
      rightSlaveTwo: -1
    constants:
      pigeonId: 13
      pigeonOnTalon: 0
      kP: 0
      kI: 0
      kD: 0
      kF: .2660
      iZone: 0
      encPPR: 4096 # CTRE mag encoder
      invertMotor: 2
  canifier:
    implemented: true
    constants:
      canId: 12
constants:
  wheelDiameter: 3.92820959548
  trackWidth: 15.75
  maxVel: 50
  maxAccel: 90
  sensorPhase: 0
