subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 1
      leftSlaveOne: 2
      leftSlaveTwo: 3
      rightMain: 5
      rightSlaveOne: 6
      rightSlaveTwo: 7
  climber:
    implemented: false
    talons:
      one: 8
  cargoshooter:
    implemented: false
    talons:
      arm: -1
      intake: -1
  constants:
    kP: 5.0
    kI: 0
    kD: 1.0
    kF: 0
    maxPos: 1475
    minPos: 915
