subsystems:
  drivetrain:
    implemented: true
    talons:
      leftMain: 2
      leftSlaveOne: 1
      leftSlaveTwo: 3
      rightMain: 7
      rightSlaveOne: 5
      rightSlaveTwo: 6
    constants:
      pigeonId: 3
      pigeonOnTalon: 1
      kP: 5.0
      kI: 0
      kD: 1.0
      kF: 0
      iZone: 0
      encPPR: 4096
      maxPos: 1475
      minPos: 915
  canifier:
    implemented: false
    constants:
      canId: 12
constants:
  wheelDiameter: 7.25
  trackWidth: 21.75
  maxVel: 25
  maxAccel: 75
